### ISSUE TITLE
Native gzip or bzip reading.

### ISSUE THREAD

**Issue by kkotyk** [SuperDARN/pydarn#11]
feature request for native gzip or bzip decompression while reading. Most of our users have their data stored in compressed formats, and RST is capable of reading in compressed formats.

**Comment by mts299** [comment]
This is already addressed, also I don't think a library should have to deal with this since we are trying to make it standalone and not completely dependent on SuperDARN choices. 

Since you are reviewing the PR #8 you should see in the unit tests I give an example of how to handle bz2 compression. The nice thing is if users use the import bz2 library that python has then don't even need to decompress but rather pyDARN reads it in as a stream. Another nice feature of this is that doesn't modify the file. 

So the user doesn't have to copy or unzip :)
Here is a test case I used it in: 
```python
import bz2
    def test_dmap_read_stream(self):
        """
        Test read_records on dmap data stream.
        The dmap data stream is formed from compressed
        bzip2 file that returns a bytes object.

         Checks:
            - returns correct data structures
            - returns expected values
        """
        # bz2 opens the compressed file into a data
        # stream of bytes without actually uncompressing the file
        with bz2.open(rawacf_stream) as fp:
            dmap_stream = fp.read()
        dmap = pydarn.DarnRead(dmap_stream, True)
        dmap_data = dmap.read_rawacf()
        self.assertIsInstance(dmap_data, collections.deque)
        self.assertIsInstance(dmap_data[0], collections.OrderedDict)
        self.assertIsInstance(dmap_data[4]['channel'], pydarn.DmapScalar)
        self.assertIsInstance(dmap_data[1]['ptab'], pydarn.DmapArray)
        self.assertIsInstance(dmap_data[7]['channel'].value, int) 
        self.assertIsInstance(dmap_data[2]['xcfd'].value, np.ndarray)
        self.assertEqual(dmap_data[0]['xcfd'].dimension, 3)
```

Also, there is gzip python library as well.

**Comment by mts299** [comment]
Side note: RST actually doesn't support reading in compression types that I am aware of 

```
make_fit 20160331.2201.00.mcm.a.rawacf.stream.bz2 > test.fitacf
Failed to get site information.
make_fit 20160331.2201.00.mcm.a.rawacf > test.fitacf
```

**Comment by egthomas** [comment]
> Side note: RST actually doesn't support reading in compression types that I am aware of

https://github.com/SuperDARN/rst/blob/master/codebase/general/src.lib/dmap.1.25/include/dmap.h#L179-L181

whether it actually works is anyone's guess

**Comment by mts299** [comment]
My bad I didn't try using gzip files, but I guess this shows how things change and to keep up with these changes means more maintenance we may not have :/ 

Thanks for the insight @egthomas

**Comment by mts299** [comment]
@kkotyk I will make a note to add this as an example in the pyDARN how to's so others can see how to read in in compressed files using python :)
