### ISSUE TITLE
SuperDARNFieldMissingError

### ISSUE THREAD

**Issue by jpreistad** [SuperDARN/pydarn#209]
When opening the map_2.5 file '20010817.n.map' downloaded using globus (November 12, 2021), I get the following error when opening:

SDarn_read = pydarn.SuperDARNRead(file)
data = SDarn_read.read_map()

SuperDARNFieldMissingError: Error: The following fields in record 653 are missing: {'vector.index', 'vector.mlat', 'vector.mlon', 'vector.kvect', 'vector.vel.sd', 'vector.stid', 'vector.vel.median', 'vector.channel'}

I am on main branch, installed with pip install pydarn on May 11, 2021.

To me this seems like a bug. I would have expected pydarn to just thrash the record at that particular time if the above fields are missing, and proceed to the next record. Instead, reading is interrupted. I suppose this does not mean that the rest of the datafile I have is corrupted? When commenting out lines 177-178 in '/dmap/superdarn.py' , I can see that this situation occur 4 times in my file.

In the meantime I will keep these lines commented, and assume that the rest of the file is ok to use. How to properly handle this situation, I am not sure of.

**Comment by carleyjmartin** [comment]
Hi @jpreistad 
Just having a quick look, your method of reading in gives me the same error. I'm assuming this might have cropped up because we don't use read_map all that much and so errors in it take time to appear, so thank you for bringing this up. 

Unfortunately, the read_map method is contained in the pydarnio library, so what I'll do is rewrite your issue over in that repo and hope someone over there picks it up.

Fortunately, however, I can get this file to be read in using read_dmap instead, with no issue.
```python
import pydarn

map_file = "/Users/carley/Documents/data/maps/20010817.n.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
```

Let me know if that helps for now!

**Comment by Shirling-VT** [comment]
@carleyjmartin This issue seems to appear multiple times in pydarn and pydarnio and is supposed to be fixed, not sure why it happens again. https://github.com/SuperDARN/pydarn/issues/122; https://github.com/SuperDARN/pyDARNio/pull/18; https://github.com/SuperDARN/pyDARNio/issues/17

**Comment by carleyjmartin** [comment]
@Shirling-VT 
Thanks for finding that!
I think this actually might be an issue with pydarn...
When reinstalling pydarn, it's only installing pydarnio version 1.0.0 where this fix doesn't exist yet.

@jpreistad 
you could also try 
`pip3 install --upgrade pydarnio`
to upgrade pydarnio to the newest version with the fix included and then run your code.

**Comment by jpreistad** [comment]
Thanks for your help folks :) As suggested, upgrading pydarnio did the job for me :)
