### ISSUE TITLE
[Bug] Matplotlib Axes objects with Fan plots

### ISSUE THREAD

**Issue by mts299** [SuperDARN/pydarn#238]
# BUG 

While trying to make a subplot with fan plot I run into the axes object issue again :( 

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [x] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Information
**python version**: 3.8.1
**OS**: ubuntu 20.01
**matplotlib version**: 3.5.1

## Example of the bug 

``` python3 
import pydarn
import datetime as dt
import matplotlib.pyplot as plt 


fig = plt.figure(figsize=(6, 6)) 
ax1 = fig.add_subplot(121, projection='polar')
pydarn.Fan.plot_fov(stid=65, date=dt.datetime(2022, 1, 8, 14, 5), grid=False, ax=ax1)

ax2 = fig.add_subplot(122, projection='polar')
pydarn.Fan.plot_fov(stid=65, date=dt.datetime(2022, 1, 8, 14, 5), grid=True, ax=ax2)
plt.tight_layout()
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/6520530/157328544-f89473a3-0352-47e9-b06e-ec72690c7fff.png)

**Comment by mts299** [comment]
We also need axes object for adding titles ... sigh

**Comment by carleyjmartin** [comment]
So this isn't working mainly because the plotting methods are all specific to the axes that we set up. If we set up the axes outside of pydarn the same way we do in the code (below) then it works to pass that in and it'll plot as expected. I don't know if it's realistic to give the plotting functions a plain polar axis and expect it to know what to do, without a very extensive refactoring of basically the whole set up from proj to plotting. However, if we really want to have subplots, we can run it like this for polar and/or geo axes:

```python
import pydarn
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt 
import cartopy.crs as ccrs

# Polar plot
date=dt.datetime(2022, 1, 8, 14, 5)
fig = plt.figure(figsize=(6, 6)) 
ax1 = fig.add_subplot(121, projection='polar')
ax1.set_ylim(90, 30)
ax1.set_yticks(np.arange(30, 90, 10))
ax1.set_xticks([0, np.radians(45), np.radians(90), np.radians(135),
                       np.radians(180), np.radians(225), np.radians(270),
                       np.radians(315)])
ax1.set_xticklabels(['00', '', '06', '', '12', '', '18', ''])
ax1.set_theta_zero_location("S")
pydarn.Fan.plot_fov(stid=65, date=date, ax=ax1)

# Geo plot
deg_from_midnight = (date.hour + date.minute / 60) / 24 * 360
pole_lat = 90
noon = -deg_from_midnight
ylocations = -5
proj = ccrs.Orthographic(noon, pole_lat)
ax2 = fig.add_subplot(122, projection=proj, aspect='auto')
ax2.gridlines(draw_labels=True)
extent = min(45e5,(abs(proj.transform_point(noon, 30, ccrs.PlateCarree())[1])))
ax2.set_extent(extents=(-extent, extent, -extent, extent), crs=proj)
pydarn.Fan.plot_fov(stid=65, date=date, ax=ax2, ccrs=ccrs, coords=pydarn.Coords.GEOGRAPHIC, projs=pydarn.Projs.GEO)
plt.tight_layout()
plt.show()
```
<img width="1230" alt="Screen Shot 2022-08-29 at 2 49 59 PM" src="https://user-images.githubusercontent.com/60905856/187296838-8b5600b5-9304-4ba5-8ff4-2658cd81b755.png">

I think most of the plotting functions now return the ax and ccrs values as standard, so edits after the fact can be done there in most cases. It's just plotting as subplots that have this issue. There's also now a fix in develop for the axes overplotting in fov, so now there's no issue plotting multiple fov or fan plots on the same axes given the axes,crss,proj and coords are set correctly. I'm going to update the docs with these examples.

Will bring this up at Thursday meeting and see what the group thinks. :D

**Comment by carleyjmartin** [comment]
Discussed in meeting, will not be adding extra support to custom axes read in initially as our axes are pretty specialised, will add above comments to documentation and this can be a record for anyone who really wants to plot subplots.
