### ISSUE TITLE
New Feature: 'True' velocity vectors for convection maps

### ISSUE THREAD

**Issue by carleyjmartin** [SuperDARN/pydarn#293]
# New Feature

**Name**: MapParams.TRUE_VELOCITY

**module**:  *maps.py* & *plotting.py*

**package**: *plotting* & *utils*

## Scope

Adding the option to calculate and plot the 'true' velocity on convection maps.
Suggested by user. 

*What will the feature do?*
Calculate and plot true vector.

*What will the feature not do?* 
Any other changes to the map plots.

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [x] Is this a minor change i.e., new small utility function?
-  [ ] Is this a major change i.e., new plotting function?
-  [x] Do you need help developing it? 
-  [ ] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done? 

### Development help

If anyone has documentation on what the 'true' velocity is that would be helpful as I only have vague descriptions of what this is supposed to be.

*If you need help please indicate what expertise you are looking for:*
- [ ] developer help with design and integration of code
- [x] scientific help with ensuring what you develop is scientifically correct/accurate
- [ ] project management to help organize what steps need to be taken to make this possible 

*Please also provide any other information you may need help with not including testing/reviewers of code*

## User Interface 

mapplot = pydarn.Maps.plot_mapdata(map_data, record=150, parameter=pydarn.MapParams.TRUE_VELOCITY)

**Comment by bharatreddy** [comment]
@billetd's comments about True vectors today: 
“merged plasma velocity vectors calculated from LOS radar measurements and the component of the fitted plasma velocity perpendicular to LOS direction”
“As true vectors directly incorporate the LOS velocity measurements from each SuperDARN radar, they offer a better representation of mesoscale plasma convection structures than the purely fitted vectors determined from electric potential solution. However, if multiple true vectors lie within the same grid cell from different radars, there is often ambiguity in the local plasma flow due to the differences in radar look directions."
Figure A1 of this paper shows the differences between each vector type:
https://agupubs.onlinelibrary.wiley.com/doi/epdf/10.1029/2001JA009124
