### ISSUE TITLE
New: A range estimation for bistatic radars / Slant Range Confusion

### ISSUE THREAD

**Issue by RemingtonRohel** [SuperDARN/pydarn#348]
# Discussion 

**Topic:** What is the meaning of slant range?

## Description

I was trying to plot a range-time plot with the vertical (range) axis showing the round-trip distance of the radio waves, however I found out that wasn't quite an option with pyDARN. The default `pydarn.range_estimation.SLANT_RANGE` gives half the round trip distance, and the `pydarn.range_estimation.HALF_SLANT` option plots 1/4 the round trip distance. I am assuming this is not the desired behaviour? I would think that SLANT_RANGE should plot the round trip distance, and HALF_SLANT half the round trip distance, i.e. distance from radar to scatter.

## Category

- [ ] User-friendly  
- [ ] Software Design
- [x] Data related
- [ ] Capabilities
- [ ] Clarity 
- [ ] Workflow

### Code

See [range_estimations.py](https://github.com/SuperDARN/pydarn/blob/develop/pydarn/utils/range_estimations.py)

**Comment by carleyjmartin** [comment]
Hi Rem, I believe they're acting as originally desired.

Half slant isn't really an 'actual measurement of distance to the scatter' it's more a commonly used estimation which is often closer to the ground scatter mapped distance rather than the straight slant range. 

Slant range should be the distance from the radar to the ionospheric scatter (so yes half the round trip distance), half slant is purely half that for no other reason than that is a good estimation close to the other way of measuring. I see that the naming might muddle this now.

No one has ever asked me for a full round trip distance, I'm not sure it makes sense to plot it in range-time plots for scientific use (i.e. it's not actually an estimation of where the scatter is but an estimation of radar-radar distance?), but I can just add a double slant range or full round trip distance parameter in if it's useful? If this is used though, I would definitely make it very clear what is plotted as I don't think the community will be used to seeing range time plots with a round trip distance on them.

**Comment by carleyjmartin** [comment]
Oops sorry I closed by accident.

**Comment by RemingtonRohel** [comment]
Okay thanks for the reply! 

Good to know about the half-slant usage, I was confused about the usefulness of that option.

It is for bistatic, I think round-trip range or straight up time of flight is probably prudent in this case. I can open a PR with any new estimations I need, I saw how you did it for half-slant so I can copy that for whichever new estimations I need. 

I appreciate the advice!

**Comment by carleyjmartin** [comment]
If you want more info on half slant - @w2naf and students at Scranton will know more (my overview above is probably terrible!) as that estimation was made for their research and like you said, is a bit more niche.

Yeah, round trip/tof makes waay more sense for bistatic, it only occurred to me later that you were probably thinking for that.

Let me know if you need anything!
